Few modifications to include: - Support of multiple kubeconfig files from the find - Usage of parameters to display usage and version - Allow Custom MAX_DEPTH as parameter

diff --git a/oc-flogin b/oc-flogin
--- a/oc-flogin
+++ b/oc-flogin
@@ -1,8 +1,17 @@
 #!/bin/bash
 # Author: rbost@redhat.com (2020)
 
-VERSION="0.0.1"
-MAX_DEPTH=${MAX_DEPTH:-5}
+VERSION="0.0.2"
+
+if [[ -n ${ZSH_VERSION} ]] && [[ ! -z ${ZSH_VERSION} ]]; then
+  INDEX_START=1
+  INDEX_OFFSET=0
+elif [[ -n $BASH_VERSION ]]; then
+  INDEX_START=0
+  INDEX_OFFSET=1
+else
+  echo "  unknown"
+fi
 
 RED='\033[0;31m'
 GREEN='\033[0;32m'
@@ -10,51 +19,97 @@ NC='\033[0m' # No Color
 
 usage() { 
     echo -e "Login to OpenShift 4 cluster using installation assets directory.\n"
-    echo -e "Usage: oc flogin PATH"
-    echo -e "Example:\n  $ oc flogin ~/installations/test-cluster"
-    echo -e "  $ oc flogin ~/installations/test-cluster/auth"
-    echo -e "  $ oc flogin version"
-    echo -e "  $ oc flogin help"
-    exit 0
+    echo -e "Usage: oc flogin -p PATH [-h|-v|-D <depth>]"
+    echo -e "  -p: Set the search PATH"
+    echo -e "  -v: Display the version"
+    echo -e "  -h: Display this help"
+    echo -e "  -D: Set the MAX_DEPTH used by the find command"
+    echo -e "Example:\n  $ oc flogin -p ~/installations/"
+    echo -e "  $ oc flogin -v"
+    echo -e "  $ oc flogin -h"
+    exit 1
 }
 
 if [ $# -eq 0 ];
 then
     echo -e "\n${RED}Error: Missing path.${NC}\n"
     usage
+else
+    while getopts "vhD:p:" OPT
+    do
+      case $OPT in
+        v)
+          echo $VERSION && exit 0
+          ;;
+        D)
+          MAX_DEPTH=${OPTARG}
+          ;;
+        p)
+          if [[ ! -d ${OPTARG} ]]
+          then
+            echo "\n${RED}Error: Invalid path '${OPTARG}'.${NC}\n"
+            usage
+          else
+            KUBE_PATH=$OPTARG
+          fi
+          ;;
+        h|help|?|*)
+          usage
+          ;;
+      esac
+    done
 fi
 
-# optional argument handling
-if [[ "$1" == "version" ]]
+MAX_DEPTH=${MAX_DEPTH:-5}
+
+# Create the Array of available KUBECONFIG
+KUBECONFIG_LIST=($(find ${KUBE_PATH} -maxdepth ${MAX_DEPTH} -type f -name kubeconfig))
+
+# Display choices & select desired kubeconfig
+length=${#KUBECONFIG_LIST[@]}
+if [[ ${length} == 1 ]]
 then
-    echo $VERSION
-    exit 0
+    KUBEINDEX=$INDEX_START
+else
+  if [[ ${length} -gt 1 ]]
+  then
+    echo "Multiple kubeconfig file found. Please select one from the list"
+    if [[ -z $ZSH_VERSION ]]; then
+      for index in "${!KUBECONFIG_LIST[@]}"; do
+        printf '[%s] %s\n' "$index" "${KUBECONFIG_LIST[index]}"
+      done
+      echo
+      read -p "Please select the kubeconfig file: " KUBEINDEX
+    else
+      for index in $(seq 1 ${length}); do
+        printf '[%s] %s\n' "$index" "${KUBECONFIG_LIST[index]}"
+      done
+      echo
+      read "KUBEINDEX?Please select the kubeconfig file: "
+    fi
+  else
+    echo -e "${RED}No kubeconfig file found in given path: ${KUBE_PATH}${NC}"
+    exit 5
+  fi
 fi
 
-if [[ "$1" == "help" ]]
-then
-    usage
-fi
-
-kubeconfigC=$(find $1 -maxdepth $MAX_DEPTH -type f -name kubeconfig 2> /dev/null | wc -l)
-kubeadminpasswordC=$(find $1 -maxdepth $MAX_DEPTH -type f -name kubeadmin-password 2> /dev/null | wc -l)
-
-if [ $kubeconfigC -eq 0 ] || [ $kubeadminpasswordC -eq 0 ];
-then
-    echo -e "${RED}No kubeconfig or kubeadmin-password file found in given path: $1${NC}"
-    exit 1
-fi
-if [ $kubeconfigC -gt 1 ] || [ $kubeadminpasswordC -gt 1 ];
-then
-    echo -e "${RED}Too many kubeconfig or kubeadmin-password files found in given path.\nPlease provide a more specific path: $1${NC}"
-    exit 1
-fi
-
-kubeconfig=$(find $1 -maxdepth $MAX_DEPTH -type f -name kubeconfig 2> /dev/null)
-kubeadminpassword=$(find $1 -maxdepth $MAX_DEPTH -type f -name kubeadmin-password 2> /dev/null)
-
-echo -e "${GREEN}Using $kubeconfig${NC}"
+kubeconfig=${KUBECONFIG_LIST[KUBEINDEX]}
+kubeadminpassword="$(dirname ${KUBECONFIG_LIST[KUBEINDEX]})/kubeadmin-password"
 server=$(grep -m1 'server: ' $kubeconfig | awk '{print $2}')
-kpass=$(cat $kubeadminpassword)
 
-oc login -u kubeadmin -p $kpass $server
+if [[ -f ${kubeadminpassword} ]]
+then
+    kpass=$(cat ${kubeadminpassword})
+    echo -e "${GREEN}Login with user/password from $kubeconfig${NC}"
+    oc login -u kubeadmin --insecure-skip-tls-verify=true  -p ${kpass} ${server}
+else
+    echo -e "${RED}No kubeadmin-password file found in given path: ${KUBE_PATH}${NC}"
+    if [[ "$_" != "$0" ]]
+    then
+      echo -e "${GREEN}Setting KUBECONFIG variable as 'export KUBECONFIG=${kubeconfig}'${NC}"
+      export KUBECONFIG=${kubeconfig}
+    else
+      echo -e "${GREEN}Please consider to Source the script by running the command: '. $*'${NC}"
+      echo -e "${GREEN}Or exporting the variable: 'export KUBECONFIG=${kubeconfig}'${NC}"
+    fi
+fi
